version: '2'

# nginx reverse proxy

services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    restart: always
    networks:
      - raspberrypi_network

networks:
  raspberrypi_network:
    external: true
